var a,initMainSelectValue=-1;function InitObject(c,b,d,f){this.m_MainId=c;this.m_SecondId=b;this.m_CarTypeId=d;this.m_CarPriceId=f}
function SelectInitObject(c,b,d,f,e){InitObject.call(this,c,b,d,f);this.m_CityId=e;this.openUrl={car:{d:"http://car.bitauto.com/",m:"http://car.bitauto.com/tree_chexing/mb_@id@/",s:"http://car.bitauto.com/@allspell@/"},price:{d:"http://price.bitauto.com/",m:"http://price.bitauto.com/keyword.aspx?keyword=@key@&mb_id=@id@&citycode=@city@",s:"http://price.bitauto.com/frame.aspx?newbrandid=@id@&citycode=@city@"}}}SelectInitObject.prototype=new InitObject;a=SelectInitObject.prototype;
a.Init=function(){var c=document.getElementById(this.m_MainId);if(c==null||c=="undefined"||c.nodeName.toString().toLowerCase()!="select")alert("init MainBrand Fault!");var b=document.getElementById(this.m_SecondId);if(b==null||b=="undefined"||b.nodeName.toString().toLowerCase()!="select")alert("init CarSerial Fault!");this.BindMainObject(JSonData.masterBrand,c);this.BindSecondObject(null,b);this.BindClickObject()};
a.BindMainObject=function(c,b){var d,f=0;if(b.options!=null||b.options.length>0)b.innerHTML="";d=new Option("\u8bf7\u9009\u62e9\u54c1\u724c",-1);b.options.add(d);if(!(c==null||c.length<1)){f=c.length;for(var e=0;e<f;e++)if(c[e].id!=-1){d=new Option(c[e].name,c[e].id);b.options.add(d)}setTimeout(function(){b.value=initMainSelectValue},1);var g=this;b.onchange=function(){g.BindMainObjectChange(g,g.m_MainId,g.m_SecondId)}}};
a.BindMainObjectChange=function(c,b,d){b=document.getElementById(b);b=b.options[b.selectedIndex].value;parseInt(b)==-1&&c.BindSecondObject(null,document.getElementById(d));var f=0;f=JSonData.masterBrand.length;for(var e=0;e<f;e++)if(JSonData.masterBrand[e].id==parseInt(b)){if(typeof BrandJsonData!="undefined"){SelectInitObject.prototype.BindSecondObjectType(JSonData.masterBrand[e],document.getElementById(d),1);break}c.BindSecondObject(JSonData.masterBrand[e].carSerial,document.getElementById(d));
break}};a.BindSecondObject=function(c,b){var d,f=0;if(b.options!=null||b.options.length>0)for(var e=0;e<b.options.length;e++)b.options.length=0;d=new Option("\u8bf7\u9009\u62e9\u7cfb\u5217",-1);b.options.add(d);if(!(c==null||c.length<1)){f=c.length;for(e=0;e<f;e++)if(c[e].id!=-1){d=new Option(c[e].name,c[e].id);b.options.add(d)}}};
a.BindSecondObjectType=function(c,b){var d;for(d=b.firstChild;d!=null;){b.removeChild(d);d=b.firstChild}d=new Option("\u8bf7\u9009\u62e9\u7cfb\u5217",-1);b.options.add(d);if(c!=null){var f;for(d=0;d<BrandJsonData.masterBrand.length;d++)if(BrandJsonData.masterBrand[d].id==c.id){f=BrandJsonData.masterBrand[d];break}for(var e=0;e<f.carBrand.length;e++){if(f.carBrand.length>1){d=document.createElement("OPTGROUP");d.label=f.carBrand[e].name;d.style.fontStyle="normal";d.style.background="#CCCCCC";d.style.textAlign=
"center";b.appendChild(d)}for(var g=0;g<c.carSerial.length;g++)if(c.carSerial[g].brandid==f.carBrand[e].id){d=document.createElement("OPTION");d.setAttribute("value",c.carSerial[g].id);d.appendChild(document.createTextNode(c.carSerial[g].name));b.appendChild(d)}}}};
a.BindClickObject=function(){var c=this,b=document.getElementById(this.m_CarTypeId);if(!(b==null||b=="undefined")){b.onclick=function(){c.CarTypeClick(c,c.m_MainId,c.m_SecondId)};if(this.m_CarPriceId!=""){b=document.getElementById(this.m_CarPriceId);if(b==null||b=="undefined")alert("Bind CarPrice Fault!");b.onclick=function(){c.CarPriceClick(c,c.m_MainId,c.m_SecondId,c.m_CityId)}}}};
a.CarTypeClick=function(c,b,d){b=document.getElementById(b);d=document.getElementById(d);b=b.options[b.selectedIndex].value;d=d.options[d.selectedIndex].value;var f="";if(d<1&&b<1){this.StaticScript(c.m_CarTypeId,0,"d");window.open(c.openUrl.car.d,"","")}else{if(d<1){f=c.openUrl.car.m.replace(/@id@/g,b);this.StaticScript(c.m_CarTypeId,b,"m")}else{var e=0;e=JSonData.masterBrand.length;f="";for(var g=0;g<e;g++)if(JSonData.masterBrand[g].id==parseInt(b)){b=JSonData.masterBrand[g].carSerial.length;for(e=
0;e<b;e++)if(JSonData.masterBrand[g].carSerial[e].id==parseInt(d)){f=JSonData.masterBrand[g].carSerial[e].allspell;break}break}if(f=="")return false;this.StaticScript(c.m_CarTypeId,d,"s");f=c.openUrl.car.s.replace(/@allspell@/g,f)}window.open(f,"","","")}};
a.CarPriceClick=function(c,b,d,f){b=document.getElementById(b);var e=document.getElementById(d);d=b.options[b.selectedIndex].value;e=e.options[e.selectedIndex].value;var g="";if(e<1&&d<1){this.StaticScript(c.m_CarPriceId,0,"d");window.open(c.openUrl.price.d,"","")}else if(e<1){b=b.options[b.selectedIndex].text;g=c.openUrl.price.m.replace(/@id@/g,d).replace(/@city@/g,f);g=g.replace(/@key@/g,encodeURI(b.slice(1,b.length)));this.StaticScript(c.m_CarPriceId,d,"m");window.open(g,"","","")}if(parseInt(e)<
0)return false;this.StaticScript(c.m_CarPriceId,e,"s");c=c.openUrl.price.s.replace(/@id@/g,e).replace(/@city@/g,f);window.open(c,"","","")};
a.StaticScript=function(c,b,d){if(!(typeof CarStaticDataObject=="undefined"||CarStaticDataObject.isStaticPage=="")){var f=CarStaticDataObject.StaticObject[CarStaticDataObject.isStaticPage];if(f!=null){var e=[];for(var g in f)e.push(g+"="+f[g]);for(var h in CarStaticDataObject.StaticObject[d][c])e.push(h+"="+CarStaticDataObject.StaticObject[d][c][h]);e.push("serialid="+b);c=CarStaticDataObject.StaticPageUrl+"?"+e.join("&");(new Image(1,1)).src=c}}};
function StartInit(c,b,d,f,e,g,h){if(c.toLowerCase()=="select"&&b.toLowerCase()=="select")return new SelectInitObject(d,f,e,g,h);alert("init Fault!")};
